functions:
  oscar:
    - oscar-remote:
        name: x-ray
        memory: 3Gi
        cpu: '1'
        image: ghcr.io/sergiolangaritabenitez/chest_x_ray
        script: script_x_ray.sh
        log_level: CRITICAL
        input:
          - path: chestray/input
            storage_provider: minio.minio
        output:
          - path: chestray/output
            storage_provider: minio.minio
    - oscar-remote:
        name: alzheimer
        memory: 3Gi
        cpu: '1'
        image: ghcr.io/sergiolangaritabenitez/alzheimer
        script: script_alzheimer.sh
        log_level: CRITICAL
        input:
          - path: alzheimer/input
            storage_provider: minio.minio
        output:
          - path: alzheimer/output
            storage_provider: minio.minio
    - oscar-remote:
        name: breast-cancer-prediction
        memory: 3Gi
        cpu: '1'
        image: ghcr.io/sergiolangaritabenitez/breastcancerprediction
        script: script_breast1.sh
        log_level: CRITICAL
        input:
          - path: bcp/input
            storage_provider: minio.minio
        output:
          - path: bcp/output/model
            storage_provider: minio.minio
    - oscar-remote:
        name: breast-cancer-prediction-graphic
        memory: 3Gi
        cpu: '1'
        image: ghcr.io/sergiolangaritabenitez/bcpgraph
        script: script_breast2.sh
        log_level: CRITICAL
        input:
          - path: bcp/input
            storage_provider: minio.minio
        output:
          - path: bcp/output/grap
            storage_provider: minio.minio
storage_providers:
  minio:
    minio:
      endpoint: 'https://minio.peaceful-haslett1.im.grycap.net'
      region: us-east-1
      access_key: accessKey
      secret_key: secretKey
      verify: true
