apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-medical-model
  labels:
    app: gradio-medical-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-medical-model
  template:
    metadata:
        labels:
          app: gradio-medical-model
    spec:
      containers:
        - name: gradio-medical-model
          image: ghcr.io/sergiolangaritabenitez/gradio_tfm
          env:
            - name: oscar_endpoint
              value: "https://eager-torvalds3.im.grycap.net"
            - name: port
              value: "30001"
          ports:
            - name: web
              containerPort: 30001
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service-medical-model  
spec:
  selector:
    app: gradio-medical-model
  ports:
    - protocol: TCP
      port: 9000
      name: service-port
      targetPort: 30001
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-medical-model
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: '999999'
spec:
  tls:
  - hosts:
    - medical.eager-torvalds3.im.grycap.net
    secretName: medical.eager-torvalds3.im.grycap.net
  rules:
  - host: medical.eager-torvalds3.im.grycap.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-medical-model
            port:
              number: 9000
